load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "computer_parts",
    srcs = ["computer_parts.cpp"],
    hdrs = ["computer_parts.h"],
    visibility = ["//lib:__subpackages__"],
)